linux4sam/at91bootstrap

include/arch/at91_pio.h
* correct address of "Peripheral Select Register 2" -> was unable to select peripheral function of portpin
Signed-off-by: Andreas Neubacher <neubacher.andreas@gmail.com>
=> fix register address

board/at91sam9g20ek/board.mk
Newer compilers default to the hard float ABI which this old board
doesn't support.  Explicitly say we want soft float (it would probably
be better to do this in some more generic place).
Signed-off-by: Mark Brown <broonie@kernel.org>
=> at91sam9g20ek: Force soft float build

driver/debug.c, include/debug.h
Hi maintainers,
Here are 3 patches to enhance the debug support:
* fix null pointer passed to dbg_printf and prints (null) instead:
```
char *p = NULL;
dbg_info("p: %s\n", p);
// p: (null)
// instead of nothing
```
* simply add the %p to dbg_printf (not essencial, convenience purpose)
```
char *p = NULL;
dbg_info("p: %p\n", p);
// p: 0x0
```
* add an dbg_hexdump function to dump memory in hexa + ascii (helpful for debugging)
Best regards,
Gaël PORTAY
=> debug: enhance support

driver/at91_slowclk.c, include/slowclk.h, main.c
The original issue that lead to this modification
is that the sama5d3 gets blocked if reset while :
OSC32BYP=1 and OSC32EN=1 and OSCSEL=1
This patch makes sure that this situation never occurs
at any moment.
----------------------------
=> sama5d3: Make slowclock bypass resistant to reset

scripts/bitfieldsparser.py, scripts/pmecc_head.py
=> Silence Python 3 errors: add paranthesis in print() calls

driver/at91_slowclk.c, main.c
On sama5d4 and sama5d2, the oscillator still has a startup time that can be
up to 1200ms. Reintroduce the interval.
Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>
=> driver: at91_slowclk: sama5d4 and sama5d2 still need a delay

Config.in.secure, driver/load_kernel.c
Linux kernel load is implemented as a 'load_function'. But load_kernel()
normally does not return to its caller. So the existing image decryption call
in main() is not applicable to kernel images. Add a kernel decryption step in
load_kernel() to allow boot of encrypted kernel images.
Tested on SAMA5D2 Xplained board.
Fixes #43.
Signed-off-by: Baruch Siach baruch@tkos.co.il
=> load_kernel: add encrypted kernel support

Config.in.secure, driver/at91_aes.c
These two commits improve the usability of secure boot with regards to endianness of keys and IV.
Patches were tested on a SAMA5D2 Xplained board.
=> Secure boot keys endianness improvements

scripts/addpmecchead.py, scripts/bitfieldsparser.py, scripts/pmecc_head.py
1. apply python 3 compatible rules in other python files.
2. make python 3 and python 2 print same output
3. misc remove duplicated condition check
=> scripts: python: fix more python3 and python2 compatible issues

config/lxdialog/check-lxdialog.sh
This brings support for finding ncurses with pkg-config, somehing that
is needed on host platforms that don't have a typical FHS directory
layout. Basically, this unbreaks the build on NixOS.
=> kconfig: update check-lxdialog.sh (copied from linux 4.6)

Makefile
Makefile: allow board.mk files to add their own files to COBJS-y and SOBJS-y
Move OBJS assignment down the code after inclusion of board-specific
makefiles, to make it possible for boards to add their own files to
compilation by addition to COBJS-y and SOBJS-y.
Signed-off-by: Sergey Organov <sorganov@gmail.com>
=> Support usefull ability for boards to add their own object files

include/arch/at91_pio.h
I think there's a typo on AT91C_PIO_CFGR_DRVSTR, in the datasheet this register is 3=high, 2=medium, 1/0=low (on master it's the other way around).
Based on:
http://www.atmel.com/Images/Atmel-11267-32-bit-Cortex-A5-Microcontroller-SAMA5D2_Datasheet.pdf
and also a physical test I did on SAMA5D27 rev. b.
=> AT91C_PIO_CFGR_DRVSTR typo fix

scripts/addpmecchead.py
Custom boards needing pmecc fails to build with e.g.:
Not support board!
Makefile:329: recipe for target '/home/peda/src/tse-850/buildroot/output/build/at91bootstrap3-v3.8.6/binaries/sama5d3_linea-nandflashboot-uboot-3.8.6.bin.pmecc' failed
This is caused by the strict checking for board names in addpmecchead.py,
so loosen up the check to avoid contaminating the script with names of
contrib boards.
Signed-off-by: Peter Rosin <peda@axentia.se>
=> scripts: addpmecchead: loosen matching for sama5d3 boards

board/sama5d2_xplained/sama5d2_xplained.c
board: sama5d2_xplained: Fix memory refresh rate at 348MHz
Memory refresh rate was incorrectly calculated.
Signed-off-by: Piotr Bugalski <bugalski.piotr@gmail.com>
=> DDR memory refresh rate fix

board/sama5d2_xplained/sama5d2_xplained.c
board: sama5d2_xplained: Fix memory calibration settings at 348MHz
According to datasheet TZQIO field has to be set to 600ns.
Value is clock dependent and needs to be adjusted for 348MHz setup.
Signed-off-by: Piotr Bugalski <bugalski.piotr@gmail.com>
=> Fix memory calibration settings at 348MHz

lib/fdt.c
If the node name length excluding nul termination is an even multiple of 4, the FDT parsing fails since the offset of the next token is incorrect.
=> Bugfix: FDT parsing fails if node name length is even multiple of 4.

Makefile
Disable set of ISO C90 functions since otherwise at91bootstrap built
with gcc7 will silently fail to boot
=> Add -fno-builtin to CPPFLAGS for gcc7

driver/ddramc.c
Memory initialization requires specific procedure which might confuse
compiler. Missing volatile keyords are causing errors when gcc 8 is
used. Issue were reproduced on XULT board, first memory access gets
broken as a result of memory access re-ordering by compiler.
Signed-off-by: Piotr Bugalski <bugalski.piotr@gmail.com>
=> ddram: add missing volatile keywords

Makefile
The build is not reproducible, because the build date is compiled in.
Avoid that, if env variable SOURCE_DATE_EPOCH is set (like some build
environments do).
The approach used here is directly taken from the reproducible builds
project. See:
https://reproducible-builds.org/docs/source-date-epoch/#makefile
Console output before:
AT91Bootstrap 3.8.12 (Mon Feb  4 13:02:06 CET 2019)
Console output after:
AT91Bootstrap 3.8.12 (2019-01-01)
If SOURCE_DATE_EPOCH is not set, the old behaviour is kept.
Signed-off-by: Alexander Dahl <post@lespocky.de>
=> build: Consider SOURCE_DATE_EPOCH

board/sama5d27_som1_ek/sama5d27_som1_ek.c, board/sama5d27_som1_ek/sama5d27_som1_ek.h
The code did set the output of pin PA27 to low.  According to SAMA5D27
SOM1 Kit1 User's Guide that is used as enable signal for an USB power
switch.  The red LED is actually connected active high to PA10 through a
MOSFET.  (Maybe that changed from an early prototype?)
If you power up the board without any bootloader, it goes to SAM-BA mode
and the red LED is on.  Switching that red LED on again in bootstrap
would give no benefit.  To see if the bootstrap was actually loaded,
this is changed to switch the green LED on now.
Fixes: a4f6043cfbb04b04d29abddb77658fbf6e66bfa0
Signed-off-by: Alexander Dahl <ada@thorsis.com>
=> board: sama5d27_som1_ek: Fix LED switch on

Makefile
Commit e60cccc4637d ("Config.in: add the dependency of
CONFIG_IMAGE_NAME") made CONFIG_IMAGE_NAME a dependency of CONFIG_FATFS.
This has the unwanted side effect of losing the target image component
of the built binary filenames when CONFIG_FATFS is not defined. For
example, what would previously have been built as
"sama5d3xek-nandflashboot-uboot-3.8.12.bin" becomes
"sama5d3xek-nandflashboot--3.8.12.bin" (note the two hyphens).
This commit fixes the problem by substituting default image names when
CONFIG_IMAGE_NAME is undefined.
=> Makefile: restore target name when CONFIG_FATFS is not set

board/sama5d27_som1_ek/sama5d27_som1_ek.c
at91_sdhc_hw_init checks whether the over-consumption erratum fix is in
place by evaluating the SDMMC_CALCR register. However, the check is a
bitwise OR, which results in the condition always being true. Use a
bitwise AND to check if the ALWYSON bit is set.
=> sama5d27_som1_ek: fix over-consumption erratum check
